[package]
name = "rysyn_egui"
version.workspace = true
edition.workspace = true

[[bin]]
name = "rysyn"
path = "src/main.rs"

[dependencies]
rysyn_ffi_bridge = { path = "../../crates/ffi_bridge" }

eframe.workspace = true
egui.workspace = true
egui_extras.workspace = true

serde.workspace = true
serde_json.workspace = true
log.workspace = true
env_logger.workspace = true

# For browser panel
dirs = "5"

# For audio file preview/waveform (optional)
# hound = "3.5"

[features]
default = []
