[package]
name = "rysyn_ffi_bridge"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["staticlib", "cdylib", "rlib"]

[dependencies]
rysyn_project = { path = "../project" }
serde.workspace = true
serde_json.workspace = true
parking_lot.workspace = true
crossbeam-channel.workspace = true
log.workspace = true

[build-dependencies]
cbindgen = "0.28"
