[package]
name = "rysyn_scripting"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
pyo3.workspace = true
rysyn_ffi_bridge = { path = "../ffi_bridge" }
rysyn_project = { path = "../project" }
serde.workspace = true
serde_json.workspace = true
log.workspace = true

[features]
default = []
python = []
